server:
  port: 8083
  servlet:
    context-path: /this-is-sp2



spring:
  thymeleaf:
    cache: false
#  security:
#    saml2:
#      relyingparty:
#        registration:
#          one:
#            signing:
#              - credentials:
#                  certificate-location: classpath:credentials/sp-certificate.crt
#                  private-key-location: classpath:credentials/sp-private.key
#            assertingparty: # this is IDP
#              entity-id: my-identity-provider-app
#              metadata-uri: http://localhost:8081/this-is-idp/saml/idp/metadata
#            singlelogout:
#              binding: POST
#              url: "{baseUrl}/saml/logout"
#              responseUrl: "{baseUrl}/saml/SingleLogout"
#            acs:
#              location: "{baseUrl}/saml/SSO"

logging:
  level:
    root: TRACE
    web: TRACE
    'sun.rmi': ERROR
    'org.apache.tomcat.util': ERROR
    'java.io': ERROR
    'org.opensaml.core': DEBUG
    'org.apache.velocity': DEBUG
